services:
  db:
    image: postgres:17.4
    container_name: postgres_db_gestor_citas
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssword12345
      POSTGRES_DB: Citas
    restart: always
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: src/Gestor.Citas.HttpApi.Host/Dockerfile
    container_name: backend_gestor_citas
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=Citas;Username=postgres;Password=P@ssword12345"
    depends_on:
      - db
    ports:
      - "5000:80"
    restart: always

  frontend:
    build:
      context: .
      dockerfile: angular/Dockerfile
    container_name: frontend_gestor_citas
    environment:
      API_URL: "http://localhost:5000"
    depends_on:
      - backend
    ports:
      - "4200:80"
    restart: always